
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzxquexihkvpqwdukfmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6eHF1ZXhpaGt2cHF3ZHVrZm1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MzAyMTAsImV4cCI6MjA2NDEwNjIxMH0.HEV-gLLBa-YtuT-WzOuf5PIBga8-opLA4iMVd_0QS0o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
